[phases.setup]
nixPkgs = ["nodejs_23", "openssl"]

[phases.install]
cmds = [
  "cd client && npm install --no-audit --no-fund",
  "cd server && npm install --no-audit --no-fund",
  "cd server && npx prisma generate"
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && npx prisma migrate deploy && npm start"
